CREATE TABLE IF NOT EXISTS authors
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(50) NOT NULL,
    nickname character varying(50) NOT NULL,
    birthday date,
    CONSTRAINT authors_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS genres
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(50) NOT NULL,
    CONSTRAINT genres_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS stories
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    genre_id bigint NOT NULL,
    name character varying(50) NOT NULL,
    CONSTRAINT stories_pkey PRIMARY KEY (id),
    CONSTRAINT story_id_genre_id FOREIGN KEY (genre_id)
        REFERENCES genres (id)
);

CREATE TABLE IF NOT EXISTS authors_stories
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    author_id bigint NOT NULL,
    story_id bigint NOT NULL,
    CONSTRAINT authors_stories_pkey PRIMARY KEY (id),
    CONSTRAINT authors_stories_id_author_id FOREIGN KEY (author_id)
        REFERENCES authors (id) MATCH SIMPLE
        ON DELETE CASCADE,
    CONSTRAINT authors_stories_id_story_id FOREIGN KEY (story_id)
        REFERENCES stories (id) MATCH SIMPLE
        ON DELETE CASCADE
);